server:
  port: 8090
  
#Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - health
        - info

# thymeleaf option
spring:
  thymeleaf:
    cache: false
    mode: HTML
# devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  security:
    user:
      name: admin
      password: admin

#enc
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    

  